### ISSUE TITLE
JavaScript Intro to Functions Lab

### ISSUE THREAD

**Issue by konomissira** [learn-co-curriculum/javascript-intro-to-functions-lab#100]
function shout(String){
  return String.toUpperCase();
}

function  whisper(String){
  return String.toLowerCase();
}
function logShout(String){
  console.log('HELLO');
} 
function logWhisper(String){
  console.log('hello');
}

function sayHiToGrandma(String){
      var hello = "hello";
    	if(hello.toLowerCase === "hello"){
    	  return "I can't hear you!";
    	}
}

function sayHiToGrandma(String){
  var HELLO = "HELLO";
  if(HELLO.toUpperCase === 'HELLO'){ 
    	return "YES INDEED";
  }
}

function sayHiToGrandma(String){
  if(String === "I love you, Grandma."){
    return "I love you, too.";
  }
}

1) sayHiToGrandma(string) returns "I can't hear you!" if `string` is lowercase:
     Error: Expected undefined to equal 'I can\'t hear you!'
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:40:37)

  2) sayHiToGrandma(string) returns "YES INDEED!" if `string` is uppercase:
     Error: Expected undefined to equal 'YES INDEED!'
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:44:37)

npm ERR! Test failed.  See above for more details.
[23:49:18] (master) javascript-intro-to-functions-lab-bootcamp-prep-001

**Comment by maxwellbenton** [comment]
Hi @konomissira,

Sorry to hear you were having difficulty with this lab. We've recently updated this lesson's instructions and added clarity around what is expected for the `sayHiToGrandma` function, which should help future students from running into the same issues.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback so we can improve our content.

Thank you!
