### ISSUE TITLE
Can't seem to return is string is lower case or upper case

### ISSUE THREAD

**Issue by clayinu** [learn-co-curriculum/javascript-intro-to-functions-lab#101]
`describe('sayHiToGrandma(string)', function() {
  it('returns "I can\'t hear you!" if `string` is lowercase', function() {
    expect(sayHiToGrandma('hello')).toEqual("I can't hear you!")
  })

  it('returns "YES INDEED!" if `string` is uppercase', function() {
    expect(sayHiToGrandma('HELLO')).toEqual("YES INDEED!")
  })

  it('returns "I love you, too." if `string` is "I love you, Grandma."`', function() {
    expect(sayHiToGrandma("I love you, Grandma.")).toEqual("I love you, too.")
  })
})
`

`function sayHiToGrandma(string) {
  string.toLowerCase() === string
  var x = "I can't hear you!"
  string = x
  return string
}
 
function sayHiToGrandma(string) {
  string.toUpperCase() === string
  var y = "YES INDEED!"
  string = y
  return string
}

function sayHiToGrandma(string) {
  string === "I love you, Grandma."
  string = "I love you, too."
  return string
}`

**Comment by maxwellbenton** [comment]
Hi @clayinu, 

Sorry to hear you were having difficulty with this lab. We've recently updated this lesson's instructions and added clarity around what is expected for the sayHiToGrandma function, which should help future students from running into the same issues.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback so we can improve our content.

Thank you!
