### ISSUE TITLE
Does someone have working code for this lab D: I am new to coding so this is my first github issue submission... D;

### ISSUE THREAD

**Issue by joshycsm** [learn-co-curriculum/javascript-intro-to-functions-lab#103]
I'm only having an issue creating the code to work for all three sayHiToGrandma tests x_x it will work for one of the three but not all three at once which is required to move on to the next lesson

function sayHiToGrandma(string) {
  var string = "hello"
  if (string.toLowerCase() === string)
    return `I can't hear you!`;
}

function sayHiToGrandma(string) {
  var string = "HELLO"
  if (string.toUpperCase() === string)
    return `YES INDEED!`
}

function sayHiToGrandma(string) {
  var string = "I love you, Grandma."
  if (string === "I love you, Grandma.")
  return `I love you, too.`
}

**Comment by maxwellbenton** [comment]
Hi @joshycsm, 

Sorry to hear you were having difficulty with this lab. We've recently updated this lesson's instructions and added clarity around what is expected for the `sayHiToGrandma` function, which should help future students from running into the same issues.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback so we can improve our content.

Thank you!
