### ISSUE TITLE
wrong file?

### ISSUE THREAD

**Issue by ayafushimi** [learn-co-curriculum/javascript-intro-to-functions-lab#11]
I think a file "javascript-intro-to-functions-lab/test/index-test.js" is a wrong file.
It's not same to what is displayed in "README.md".

For example, the text below doesn't exist in this file.

'''
const expect = require('expect')
const fs = require('fs')
const jsdom = require('mocha-jsdom')
const path = require('path')
'''

**Comment by AnnJohn** [comment]
thanks for raising @ayafushimi. this should be updated
