### ISSUE TITLE
test 'passed' after incorrectly coding 1 of 7 

### ISSUE THREAD

**Issue by thesilentc** [learn-co-curriculum/javascript-intro-to-functions-lab#14]
After completing the 

> **function shout(string) {}**

 test (incorrectly, at that) the test declared that the lab had "passed" on Learn.co, but 'failed' in the Atom IDE.

**Comment by bhollan** [comment]
This sometimes happens when a different timeout error occurs.

If you can provide the code that gave the false positive, that would help us determine if something needs to be changed.
