### ISSUE TITLE
README screenshots inconsistent with tests 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/javascript-intro-to-functions-lab#19]
@aturkewi The screenshots of the `learn test` output in the README show 4 total tests, but the lab has since been updated to have 7 total tests. I have had several students from different tracks asking if that is an issue. I think it would be helpful to update the screenshots to reflect the current tests. 

Attached are updated screenshots for quick reference: 
<img width="672" alt="screen shot 2017-01-31 at 11 54 18 am" src="https://cloud.githubusercontent.com/assets/16696437/22492966/a8cc08b8-e867-11e6-8f54-4f0d621457f4.png">
<img width="666" alt="screen shot 2017-01-31 at 10 13 36 am" src="https://cloud.githubusercontent.com/assets/16696437/22492971/aa4b3772-e867-11e6-84c6-cdbdcc92419a.png">

**Comment by aturkewi** [comment]
Fixed in PR #23 
Thanks!
