### ISSUE TITLE
Lesson folder not shown in IDE

### ISSUE THREAD

**Issue by chriszubrod** [learn-co-curriculum/javascript-intro-to-functions-lab#20]
After I run Open javascript-intro-to-functions-lab-bootcamp-prep-000, the lesson folder does not appear on the left hand side of the IDE. I have tried logging out, and re-opening the lesson. Still not working out for me. Any suggestions?

Thanks.

**Comment by yakovkiff** [comment]
Same problem.

**Comment by yakovkiff** [comment]
I uninstalled the IDE and then downloaded and installed it again.  Seems to have taken care of the folder problem.  But now my code always comes back as all errors, even parts that I know are correct because they worked in the browser console.
