### ISSUE TITLE
index-test describe code does not match Readme.md or course page

### ISSUE THREAD

**Issue by dsieburgh** [learn-co-curriculum/javascript-intro-to-functions-lab#24]
In the course work and readme file, the index-test code is written:
```javascript 
describe('shout(string)', () => {
```
but in the included files it is written"
```javascript
describe('shout(string)', function() {
```

**Comment by sgharms** [comment]
In JavaScript we see both styles of function declaration being used!

They mean the same thing! We'll close this issue accordingly.
