### ISSUE TITLE
Intro to Functions Lab

### ISSUE THREAD

**Issue by cmaysen** [learn-co-curriculum/javascript-intro-to-functions-lab#28]
I'm not sure how to combine if statements with strings

**Comment by seanelwood** [comment]
I found a typo in the lesson. (highlighted in screenshot)
where the lesson says "Now open up test/index-test.js."
this should be changed to root.js, not index-test.js
![screen-shot-2017-03-12-at-12 54 43-pm](https://cloud.githubusercontent.com/assets/16353503/23834384/b36c93a2-0723-11e7-83f6-dac4896b327f.gif)
