### ISSUE TITLE
Problem Completing Lab

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/javascript-intro-to-functions-lab#32]
I am having trouble completing my labs. This message pops up. 
<img width="1278" alt="screen shot 2017-03-18 at 12 48 53 pm" src="https://cloud.githubusercontent.com/assets/26261308/24074152/728a0be8-0bd9-11e7-96cb-7162449f67b8.png">

**Comment by JessRudder** [comment]
@jimnshea if you're still having an issue, please use the "Ask a Question" feature to get live help from a Learn Expert.
