### ISSUE TITLE
Incorrect file referenced?

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/javascript-intro-to-functions-lab#45]
Hello, I was looking at the beginning of the code along. The file referenced does not have 
`global.expect = require('expect');
const babel = require('babel-core');
const jsdom = require('jsdom');
const path = require('path');`

 It appears the wrong file is referenced (index-test.js) instead of root.js which does have the libaries referenced.

**Comment by BlecKet** [comment]
Yeah, I agree!
