### ISSUE TITLE
Folders not properly loading in Learn IDE

### ISSUE THREAD

**Issue by kpie11** [learn-co-curriculum/javascript-intro-to-functions-lab#48]
![image](https://cloud.githubusercontent.com/assets/27033357/24982183/f5f150c6-1f94-11e7-9016-27b70821f3de.png)

**Comment by JessRudder** [comment]
@kpie11 if you're still having issues with the IDE, please use the "Ask a Question" feature in Learn to get live help from a Learn Expert.
