### ISSUE TITLE
I finished the lab and passed it but it won't let me move to the next lesson.

### ISSUE THREAD

**Issue by lekan20** [learn-co-curriculum/javascript-intro-to-functions-lab#55]
For some reason Fork this lab won't show as complete.

**Comment by JessRudder** [comment]
@lekan20 some times it can take a while for those messages to get from GitHub to Learn for the lights to go green.  Usually a page refresh does the trick.  If not, there might be a larger delay.  In those instances, just keep moving forward and the lights will catch up later.
