### ISSUE TITLE
Difference between webpage and README.md

### ISSUE THREAD

**Issue by SchecterHXC** [learn-co-curriculum/javascript-intro-to-functions-lab#59]
![webpage](https://user-images.githubusercontent.com/29413276/27110223-bcf6f638-5075-11e7-8c22-491e81b990b1.PNG)

|| The above is correct, but on the README.md file, it looks like this:

![readme](https://user-images.githubusercontent.com/29413276/27110242-d832f92e-5075-11e7-823d-8f67f09f3580.PNG)

The issue is that both of these files exist, and part of the reference code is in the root.js file, and the other part is in the index-test.js file

Please resolve this issue to make the lab a little more coherent for some people.

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like this may have been corrected, but never closed--so I'm going to close it for now.

As always, thanks for contributing! 💙
