### ISSUE TITLE
sayHiToGrandma

### ISSUE THREAD

**Issue by daafbleumink** [learn-co-curriculum/javascript-intro-to-functions-lab#67]
Hey I'm trying to get the function working that's supposed to say "I can't hear you" when all you enter is lowercase letters.
I'm not quite sure what the function's supposed to be. Could someone help me?

**Comment by dbrow437** [comment]
Hi Daafiejd,

I'm stuck here too.  Did you ever get an answer?

**Comment by narsimha-khedkar** [comment]
function sayHiToGrandma(string){
  if (string === string.toLowerCase()){
    return ("I can't hear you!")
  }
    else if (string===string.toUpperCase()) {
      return ("YES INDEED!")
    }
      else {
        return ("I love you, too.")
      }
}
