### ISSUE TITLE
JavaScript intro to functions lab

### ISSUE THREAD

**Issue by JamesDRenna** [learn-co-curriculum/javascript-intro-to-functions-lab#7]
The README.md and index-test.js files do not correspond. The README file incorrectly describes the top of the test file, the directions for the first part of the test do not satisfy the requirements of the test (the description has an exclamation point, for example), the picture used shows a four-part test (the actual test is seven parts), etc.

**Comment by AnnJohn** [comment]
thanks for raising @JamesDRenna. this should be updated.
