### ISSUE TITLE
permission denied when I tried opening up test/root.js

### ISSUE THREAD

**Issue by stolenEraser** [learn-co-curriculum/javascript-intro-to-functions-lab#71]

**Comment by drakeltheryuujin** [comment]
Hi there @carahvillacampa,

Would you mind providing a bit more detail about the issue? Things that are especially useful:

- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
- What's your operating system? Which version?
- Are you using the Learn IDE or a local development environment?
- A stack trace of any errors.

Thanks! 💙

**Comment by sgharms** [comment]
@carahvillacampa 

We're going to close this issue since we've not heard back. Please re-open if needed.
