### ISSUE TITLE
Intro to Functions Lab-Cannot get last test to pass

### ISSUE THREAD

**Issue by 5Lions** [learn-co-curriculum/javascript-intro-to-functions-lab#72]
Hi there:
i'm wracking my brain to figure out why the last test won't pass, i've reordered conditionals, tried using a mixedcase example like the lab and the below keeps returning "YES, INDEED!" for sayHiToGrandma("I love you, Grandma.") and I can't figure out why.  
Many Thanks!

### Below is my code and the error message.

``` function sayHiToGrandma(string) {
  if (string === string.toLowerCase()) {
    return ("I can't hear you!");
  } if (string === string.toUpperCase()); {
    return ("YES INDEED!");
  } if (string === 'I love you, Grandma.'); {
    return ("I love you, too.");
  }
}
sayHiToGrandma(whisper('heLlo'));
sayHiToGrandma(shout('HEllO'));
sayHiToGrandma("I love you, Grandma."); ```

### error message

``` 1) sayHiToGrandma(string) returns "I love you, too." if `string` is "I love you, Grandma."`:
      Error: Expected 'YES INDEED!' to equal 'I love you, too.'
      + expected - actual
      -YES INDEED!
      +I love you, too.
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:48:52) ```

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like you've already completed the lesson, but for future reference, raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

This type of issue would be perfect for the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.

If, after consulting the Help Center and AAQ, you feel that it is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
