### ISSUE TITLE
Technical Application Submitted Early

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/javascript-intro-to-functions-lab#73]
Hello,

I had just started the technical application and finished the string chapter, then on the next page I was issued a prompt in the console, that read something like, "You are about to open a lesson, beyond your current lesson." It prompted a '[Yn]' response, so I type 'Y', and then it submitted all of my materials and I cannot go back and resubmit. Can someone please help me if I can solve this, or perhaps have it reset?

Thanks,

Nate

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an issue with the Learn platform. Raising issues on GitHub should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

Please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

Thanks! 💙
