### ISSUE TITLE
sayHiToGrandma index-test.js expects wrong string return

### ISSUE THREAD

**Issue by hollowprince** [learn-co-curriculum/javascript-intro-to-functions-lab#74]
As the title says, in the sayHiToGrandma the index-test.js expects strings such as "I can't hear you" or "YES INDEED" when calling the sayHiToGrandma string calls "hello" or "HELLO" respectively. Another example is in the last text, calling the string returns "I love you Grandma." when expecting "I love you too." instead of expecting "I love you Grandma" then returning "I love you too." Makes the lab require going to index-test.js to change the expected values to the _actual_ string values. I may be wrong and just inept, but it seems like the lab tests are broken.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, it seems that there is nothing wrong with the tests for `sayHiToGrandma`, so I'm going to close it for now.
If you feel that this is a mistake, with some more clarification, I'd be happy to take a second look!
As always, thanks for contributing! 💙
