### ISSUE TITLE
The Code-Along section needs to be updated.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/javascript-intro-to-functions-lab#75]
Hi. The Code-Along portion of this lab makes reference to a "sandbox analogy from earlier". However, this sandbox analogy isn't in any of the previous lessons in the Bootcamp Prep.

I don't know if the analogy is in one of the Bootcamp lessons, rather than the Bootcamp Prep lessons, or if it just doesn't exist anymore. Either way, the lesson needs to be updated, if anyone has the time.

Thanks and good luck!

Steven

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙

**Comment by Sdcrouse** [comment]
I looked over the updated README. I think it's all good! Thanks for taking care of that.

Steven
