### ISSUE TITLE
Mocha Code Snippets Use Incorrect Syntax

### ISSUE THREAD

**Issue by Tokuhisa1** [learn-co-curriculum/javascript-intro-to-functions-lab#77]
The first two code snippets referencing test/index-test.js use an incorrect mixing of ES5 and ES6+ syntax, i.e. using the function keyword in direct conjunction with the "husky" arrow.

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like the syntax was updated in pull request #3 

Thank you for your feedback! 💙
