### ISSUE TITLE
Technical Application JS Falsely Shows All Lessons Completed

### ISSUE THREAD

**Issue by trevor-jameson** [learn-co-curriculum/javascript-intro-to-functions-lab#78]
An alert stating that all lessons had been completed appeared after only completing the "Strings" lab and opening "Intro to Functions." All courses listed as complete in dropdown menu. See screenshot.

<img width="1440" alt="false_completion_alert 2018-06-18 at 5 50 54 pm" src="https://user-images.githubusercontent.com/19979089/41564293-508a2f28-7320-11e8-926f-a2573125e541.png">

**Comment by drakeltheryuujin** [comment]
I'm having difficulty reproducing the issue, so I'm going to close it for now.
If you feel that the issue has not been resolved, we'd be happy to take a second look!
Thanks for contributing! 💙
