### ISSUE TITLE
index-test.js does not match the lesson

### ISSUE THREAD

**Issue by JamesSegarra3** [learn-co-curriculum/javascript-intro-to-functions-lab#8]
The description in the Readme.md and the learn.co website do not match the actual content of the lab indexes.

**Comment by JamesSegarra3** [comment]
I tried to refork the lab and now I get a ruby error

// ♥ learn open javascript-intro-to-functions-lab-js-apply-000  
/usr/local/rvm/gems/ruby-2.2.3@global/gems/rubygems-bundler-1.4.4/lib/rubyge
ms-bundler/noexec.rb:5:in `pwd': No such file or directory - getcwd (Errno::
ENOENT)                                                                     
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/rubygems-bundler-1.4
.4/lib/rubygems-bundler/noexec.rb:5:in`class:Noexec'  
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/rubygems-bundler-1.4
.4/lib/rubygems-bundler/noexec.rb:3:in `<top (required)>'                   
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubyg
ems/core_ext/kernel_require.rb:128:in`require'  
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubyg
ems/core_ext/kernel_require.rb:128:in `rescue in require'                   
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubyg
ems/core_ext/kernel_require.rb:39:in`require'  
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/rubygems-bundler-1.4
.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'       
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/executable-hooks-1.3
.2/lib/executable-hooks/hooks.rb:50:in`call'  
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/executable-hooks-1.3
.2/lib/executable-hooks/hooks.rb:50:in `block in run'                       
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/executable-hooks-1.3
.2/lib/executable-hooks/hooks.rb:49:in`each'  
        from /usr/local/rvm/gems/ruby-2.2.3@global/gems/executable-hooks-1.3
.2/lib/executable-hooks/hooks.rb:49:in `run'                                
        from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:10:in 
`<main>'

**Comment by HarlemSquirrel** [comment]
I've had several students notice this as well.
@aturkewi

**Comment by AnnJohn** [comment]
hi @HarlemSquirrel and @jsegarra3 this looks like a product issue. I just re-deployed the lab so that might help, but if not then we'll relay this to product. thanks!
