### ISSUE TITLE
Attached problem with this Lab.

### ISSUE THREAD

**Issue by FSGh2018** [learn-co-curriculum/javascript-intro-to-functions-lab#82]
Attached problem with this Lab.

**Comment by FSGh2018** [comment]
[issue 2018-07-25.txt](https://github.com/learn-co-curriculum/javascript-intro-to-functions-lab/files/2231796/issue.2018-07-25.txt)

**Comment by FSGh2018** [comment]
Attached problem with this Lab.

**Comment by sgharms** [comment]
Try discussing your issue via the [Ask a Question][AAQ] tool instead of a study group.

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson

**Comment by sgharms** [comment]
As this does not appear to be a flaw in the curriculum, we're going to close this issues.

Please re-open if you and a coach find a bug in the code.
