### ISSUE TITLE
how to check if the String is lowercase or uppercase?

### ISSUE THREAD

**Issue by miricoder** [learn-co-curriculum/javascript-intro-to-functions-lab#84]
Hello, 

I would like to test to see if the strings are lower or uppercase when i change them, i know what code i need to test them with for example 
**var uppercase = "HELLO!"
uppercase.toUpperCase() === uppercase,** which is in the lab, however i don't know which platform i should run it to test at. Please help me.

Regards,

**Comment by maxwellbenton** [comment]
Hi @miricoder,

This lab already has tests built in that will confirm if you have successfully modified a string. Write a whisper method that takes in a string and returns a lowercase version of it. Do the same for `logShout`, but return the uppercase.  If the methods return the correct value, the tests will pass when you run `learn`. 

I'm going to close this issue as it is not related to a problem with the materials. Feel free to reach out for help using the `Ask a Question` feature on learn.co and an online instructor will be able to assist you.
