### ISSUE TITLE
Problem submitting

### ISSUE THREAD

**Issue by Agfeynman** [learn-co-curriculum/javascript-intro-to-functions-lab#85]
I execute learn test and passes all tests but the check mark in the right sidebar doesnt change. I execute learn submit and says I didn't make it. It's a bug?
![image](https://user-images.githubusercontent.com/18236517/44333775-1a56f900-a470-11e8-804e-de44bff02229.png)
![image](https://user-images.githubusercontent.com/18236517/44333801-28a51500-a470-11e8-93cd-80c7fed0c0be.png)

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a fix to the Learn platform. [Raising issues on GitHub][raise] should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.) If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
