### ISSUE TITLE
sayHiToGrandma

### ISSUE THREAD

**Issue by Gradius93** [learn-co-curriculum/javascript-intro-to-functions-lab#88]
Hi, i've been having problems with this code test for a while now. I've already asked a question in the questions that need help option, and when i got answers they still didn't work. I've now tried to ask more questions and it still won't let me. Can you help please?

**Comment by maxwellbenton** [comment]
Hi @Gradius93,

Sorry to hear you were having difficulty with this lab, and I hope you were able to find the solution. We've recently updated this lesson's instructions to provide more clarity and guidance around solving the last few tests to help future students get through this content.

We apologize for any frustration this may have caused, but we appreciate you taking the time to give us this feedback.

Thank you!
Thank you!
