### ISSUE TITLE
Results not outputting properly on IDE 

### ISSUE THREAD

**Issue by tealoui3** [learn-co-curriculum/javascript-intro-to-functions-lab#90]
Results not outputting properly on Javascript's Intro to Functions lab. Expecting terminal to output usual passing/failing template specifying errors, instead getting:

(master) javascript-intro-to-functions-lab-js-intro-000
// ♥ /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method
NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
^C

**Comment by maxwellbenton** [comment]
Hi @tealoui3,

Sorry to hear that this lab wasn't working for you. I was unfortunately unable to replicate this issue, but we've recently updated this lesson's instructions and have confirmed that the tests are working as expected now.

We apologize for any frustration this may have caused, but we appreciate you taking the time to give us this feedback.

Thank you!
