### ISSUE TITLE
grammar issue

### ISSUE THREAD

**Issue by joshuamsmith413** [learn-co-curriculum/javascript-intro-to-functions-lab#91]
We're going to use what we learn practicing speaking in this way to write another function, sayHiToGrandma(), which takes our new-found speaking ability to greet our grandmother. 

This sentence, located under "Your Turn" is hard to read. specifically the three verbs in a row (learn, practicing, speaking) could be changed to be a little bitt more readable. 
Thanks!

**Comment by maxwellbenton** [comment]
Hi @joshuamsmith413, 

Thank you for providing this feedback. We've recently updated this lesson's instructions and updated the instructions under `Your Turn` based on the feedback you've provided.

Thank you for contributing!
