### ISSUE TITLE
Trouble with Intro to Functions Lab

### ISSUE THREAD

**Issue by arl480** [learn-co-curriculum/javascript-intro-to-functions-lab#92]
Hi, having problem with this code 
`function sayHiToGrandma(string) {
   if (string === string.toLowerCase());
   return ("I can't hear you!");
}
  function sayHiToGrandma(string) {
  if (string === string.toUpperCase());
 return ("YES INDEED!"); 
} 

 function sayHiToGrandma(string) {
if (string === "I love you, Grandma.");
 return ('I love you, too.');
   
 }`

I keep getting error:
`1) sayHiToGrandma(string) returns "I can't hear you!" if `string` is lowercase:

      Error: Expected 'I love you, too.' to equal 'I can\'t hear you!'
      + expected - actual

      -I love you, too.
      +I can't hear you!

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:40:37)

  2) sayHiToGrandma(string) returns "YES INDEED!" if `string` is uppercase:

      Error: Expected 'I love you, too.' to equal 'YES INDEED!'
      + expected - actual

      -I love you, too.
      +YES INDEED!

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:44:37)

npm ERR! Test failed.  See above for more details.
[22:08:06] (master) javascript-intro-to-functions-lab-js-apply-000
// ♥ learn test

> java-script-intro-to-functions-lab@0.1.0 test /home/confident-database-3099/javascript-intro-to-functions-lab-js-apply-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

HELLO-_,------,
hello__,------,\
 5   __,------, )
 2   __|  /\_/\
 0   _~|_( x .x)
     _ ""  ""

  5 passing (192ms)
  2 failing

  1) sayHiToGrandma(string) returns "I can't hear you!" if `string` is lowercase:

      Error: Expected 'I love you, too.' to equal 'I can\'t hear you!'
      + expected - actual

      -I love you, too.
      +I can't hear you!

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:40:37)

  2) sayHiToGrandma(string) returns "YES INDEED!" if `string` is uppercase:

      Error: Expected 'I love you, too.' to equal 'YES INDEED!'
      + expected - actual

      -I love you, too.
      +YES INDEED!
`

Any help would be appreciated! Thanks!

**Comment by maxwellbenton** [comment]
Hi @arl480, 

Sorry to hear you were having difficulty with this lab, and I hope you were able to find the solution. We've recently updated this lesson's instructions to provide more clarity and guidance around solving the last few tests to help future students get through this content.

We apologize for any frustration this may have caused, but we appreciate you taking the time to give us this feedback.

Thank you!
