### ISSUE TITLE
Function Description

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/javascript-intro-to-functions-lab#93]
> logShout(string) calls console.log() its one argument in all caps

"Its" is possessive and in context quite confusing. This complicates the test by being unnecessarily vague.

**Comment by maxwellbenton** [comment]
Hi @alouiseme, 

Thank you for this feedback. We've recently updated this lesson's instructions to provide more clarity and guidance and modified the messages in the `logShout` and `logWhisper` tests based on your feedback.

Thank you for contributing to this lesson!
