### ISSUE TITLE
can not open ask a question

### ISSUE THREAD

**Issue by buildafriend** [learn-co-curriculum/javascript-intro-to-functions-lab#96]
I can not open ask a question during my prep course

**Comment by maxwellbenton** [comment]
Hi @buildafriend, 

Sorry to hear you were having difficulty accessing Ask a Question. I hope you were able to find the solution. If you are still working on any Learn content and encountering this issue, please reach out to support@learn.co and they will be able to assist you more rapidly.

We apologize for any frustration this may have caused, but we appreciate you taking the time to give us this feedback.

Thank you!
